### PR TITLE
add default template for ElementVirtual

### LINKED ISSUE #7: Installing via composer provides no templates? (custom theme)
Installed via composer and after dev/build and reloading page with a virtual object on it I get this:

> [USER WARNING] NONE OF THE FOLLOWING TEMPLATES COULD BE FOUND: ARRAY ( [0] => DNADESIGN\ELEMENTALVIRTUAL\MODEL\ELEMENTVIRTUAL [1] => DNADESIGN\ELEMENTALVIRTUAL\MODEL\ELEMENTVIRTUAL ) IN THEMES "ARRAY ( [0] => MYTHEME [1] => $DEFAULT ) "

This template doesn't actually seem to exist in the codebase either. Where should we find this?

Theme set via /mysite/_config/theme.yml as follows:

```
---
Name: mytheme
---
SilverStripe\View\SSViewer:
  themes:
    - 'mytheme'
    - '$default'
```

Any idea? I guess I could build that path inside the theme directory but docs don't suggest the need for that, and it would be a rather polluting path. Should this not be in the module template directory?

### PR DESCRIPTION
**Pull request by korthjp17**
duplicated the ElementContent template from that repo.

Fixes #7

### CODE REVIEW

**Comment by a2nt** [comment]
Had the same issue and fixed it in the same way

**Comment by korthjp17** [comment]
Unfortunately, this may not be the best way to fix it. We noticed that it would pull other elements in other than just the ElementContent. Using one template probably won't work.

**Comment by wilr** [comment]
Correct, `ElementVirtual` if I'm not mistaken should have a renderWith method which returns the linked element template. It shouldn't need a template of its' own. Probably worth investigating why the linked element isn't being rendered (perhaps due to draft/live stages?)

**Comment by korthjp17** [comment]
I don't recall seeing a `renderWith` method in there, unless it's in an extension that I missed.

**Comment by wilr** [comment]
Hmm perhaps it relies on https://github.com/dnadesign/silverstripe-elemental-virtual/blob/master/templates/ElementalHolder_VirtualLinked.ss#L2 `$Element` should render the element

**Comment by phptek** [comment]
If I add a single `VirtualElement` to a page, and dump out its templates:

```
array(4) {
  [0]=>
  string(61) "DNADesign\ElementalVirtual\Model\ElementVirtual_ElementalArea"
  [1]=>
  string(47) "DNADesign\ElementalVirtual\Model\ElementVirtual"
  [2]=>
  string(61) "DNADesign\ElementalVirtual\Model\ElementVirtual_ElementalArea"
  [3]=>
  string(47) "DNADesign\ElementalVirtual\Model\ElementVirtual"
}
```

Despite what is supposed to happen, the module is trying to find/use a template called "ElementVirtual.ss". 

The only way I've found around this is to create a "ElementVirtual_ElementalArea.ss" template in my theme and use fugly template logic to decide which template to render. If anyone has any better ideas, I'm all ears :-)

**Comment by emmettdn** [comment]
It seems to be missing a way to render the linked element.

Can we override the `forTemplate()` method in `ElementVirtual` to use the linked element's `forTemplate()` method instead?

```
public function forTemplate($holder = true)
    {
        if ($linked = $this->LinkedElement()) {
            return $linked->forTemplate();
        }
        return null;
    }
```

**Comment by christopherdarling** [comment]
An alternative that I found to work well was to add DNADesign\ElementalVirtual\Model\ElementVirtual.ss with content

```
$LinkedElement
```

Which does essentially the same as #11 but through the template

**Comment by korthjp17** [comment]
It seems @christopherdarling's suggestion worked. I've updated the default template for this PR.

**Pull request merged**
